### ISSUE TITLE
Why is this happening? Is it because of rotation.txt?

### ISSUE THREAD

**Issue by Andyli0123** [WarzoneMC/Warzone#438]
If it is because of rotation.txt, what should I enter?

> [12:15:57 ERROR]: Error occurred while enabling TGM v1.0-SNAPSHOT (Is it up to date?)
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_201]
        at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_201]
        at network.warzone.tgm.map.MapRotationFile.cycle(MapRotationFile.java:31) ~[?:?]
        at network.warzone.tgm.match.MatchManager.cycleNextMatch(MatchManager.java:76) ~[?:?]
        at network.warzone.tgm.TGM.onEnable(TGM.java:111) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1611]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1611]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1611]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1611]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1611]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1611]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1611]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1611]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1611]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1611]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by BennyDoesTheStuff** [comment]
What does your rotation.txt look like?

**Comment by jellz** [comment]
Can you attach the contents of your rotation.txt file? What maps are you using?
